special_offer_url:
  user:
    email: samcfinan@gmail.com
    password: 5j5UcdAuNCkz
  purchases:
    - id: 14790
      quantity: 2
    - id: 383695
      quantity: 3
  payment:
    # Do not include spaces
    card_num: 4141909023421234
    # ex. 231
    card_cvv: 231
    # MM
    card_exp_month: 03
    # YY
    card_exp_year: 22
    # 'Visa' | 'MasterCard' | 'American Express'
    card_type:
  